export default {
    "login": "Makender103",
    "id": 37935019,
    "node_id": "MDQ6VXNlcjM3OTM1MDE5",
    "avatar_url": "https://avatars0.githubusercontent.com/u/37935019?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Makender103",
    "html_url": "https://github.com/Makender103",
    "followers_url": "https://api.github.com/users/Makender103/followers",
    "following_url": "https://api.github.com/users/Makender103/following{/other_user}",
    "gists_url": "https://api.github.com/users/Makender103/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Makender103/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Makender103/subscriptions",
    "organizations_url": "https://api.github.com/users/Makender103/orgs",
    "repos_url": "https://api.github.com/users/Makender103/repos",
    "events_url": "https://api.github.com/users/Makender103/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Makender103/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Marc kender R. Jean Charles",
    "company": "UFFS",
    "blog": "Www.mjcode.net",
    "location": "Brazil",
    "email": null,
    "hireable": true,
    "bio": " ●Computer Science Student\r\n\r\n ●Front-End Developer :  ReactJS | ReactNative \r\n\r\n ●Javascript Developer\r\n\r\n● NodeJs Student",
    "twitter_username": "Makender103",
    "public_repos": 22,
    "public_gists": 0,
    "followers": 12,
    "following": 14,
    "created_at": "2018-03-30T14:53:37Z",
    "updated_at": "2020-10-30T13:10:01Z"
};
